import type { Metadata } from "next";
import { Roboto, Jersey_25 } from "next/font/google";
import "./globals.css";

const jersey = Jersey_25({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--jersey",
});

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jersey.variable} ${roboto.variable}`}>
      <body className="font-roboto">{children}</body>
    </html>
  );
}
