import type { Metadata } from "next";
import { Roboto, Jersey_25 } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const jersey = Jersey_25({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--jersey",
});

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`antialiased ${jersey.variable} ${roboto.variable}`}
    >
      <body className="font-roboto">
        <div className="flex flex-col items-start justify-center bg-zinc-950 min-h-screen text-white">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
